# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: weather forecasting

on:
  push:
    branches: [ "weatherforecastkva" ]
  pull_request:
    branches: [ "weatherforecastkva" ]

permissions:
  contents: read

jobs:

  test:
    
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Test the new code
        uses: actions/checkout@v3

  
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      # Runs a set of commands using the runners shell
      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.txt
      
      - name: Run test cases
        run: |
          python -m pytest test.py
